# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Decidim Awesome Module
author: PokeCode
email: info@pokecode.net
address: Carrer Concepció Arenal 165 08027 Barcelona
phone_number: +34 663 191 025
description: >- # this means to ignore newlines until "baseurl:"
  This plugin allows the administrators to expand the possibilities of Decidim beyond some
  existing limitations. All tweaks are provided in a optional fashion with granular 
  permissions that let the administrator to choose exactly where to apply those mods. Some 
  tweaks can be applied to any assembly, other in an specific participatory process or even 
  in type of component only.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: openpoke
decidim_username: openpoke
telegram_username: openpoke

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false
  
sidebars:
  - sidebar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
